### ISSUE TITLE
ModelLoadAndPredict Operator input error

### ISSUE THREAD

**Issue by fhoda** [astronomer/airflow-provider-mlflow#19]
Have not identified conditions that cause this but seems that supplying a list of values to the `data` param causes this error often
```
Traceback (most recent call last):
File "/tmp/venv8sy_8x7t/script.py", line 85, in <module>
res = _model_load_and_predict(*arg_dict["args"], **arg_dict["kwargs"])
 File "/tmp/venv8sy_8x7t/script.py", line 76, in _model_load_and_predict
 result = loaded_model.predict(data=nparray(data))
File "/tmp/venv8sy_8x7t/lib/python3.9/site-packages/mlflow/pyfunc/__init__.py", line 412, in predict
data = _enforce_schema(data, input_schema)
File "/tmp/venv8sy_8x7t/lib/python3.9/site-packages/mlflow/models/utils.py", line 649, in _enforce_schema
 raise MlflowException(message)
mlflow.exceptions.MlflowException: Model is missing inputs ['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'petal_width_cm']. Note that there were extra inputs: [0, 1, 2, 3]
```

This seems to be related to this issue in MLflow https://github.com/mlflow/mlflow/issues/7215

**Comment by fhoda** [comment]
The referenced mlflow issue has a workaround  https://github.com/mlflow/mlflow/issues/7215#issuecomment-1303129920 which seems to be working in local tests.
