### ISSUE TITLE
ModelLoadAndPredictOperator ambiguous DataFrame error

### ISSUE THREAD

**Issue by fhoda** [astronomer/airflow-provider-mlflow#20]
When supplying pandas DataFrame input to the operator's `data` param this error occurs

```
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -     self.run()
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.9/threading.py", line 917, in run
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -     self._target(*self._args, **self._kwargs)
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/listener.py", line 90, in on_running
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -     task_instance_copy.render_templates()
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -     original_task.render_template_fields(context)
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -     self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.9/site-packages/airflow/utils/session.py", line 75, in wrapper
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -     return func(*args, session=session, **kwargs)
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 599, in _do_render_template_fields
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -     if not value:
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 1527, in __nonzero__
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING -     raise ValueError(
[2023-04-11, 17:47:51 UTC] {logging_mixin.py:137} WARNING - ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by fhoda** [comment]
Running the same function on the same model outside of Airflow **does not** produce the same error.
